ansys/pyfluent-visualization

pyproject.toml, tests/test_metadata.py
=> Bump version to v0.4.1

.github/workflows/nightly-doc-build.yml
Pyfluent core repo has the same configuartion.
=> Run nightly doc build with both 22.2 and 23.1 Fluent image

.github/workflows/ci_cd.yml, pyproject.toml, tests/test_metadata.py
=> Bump version 0.6.dev0

pyproject.toml, tests/test_metadata.py
Contains the latest changes w.r.t. pathlines and FieldData.
=> Bump version to v0.6.dev1

pyproject.toml, tests/test_metadata.py
This will include the psutil fix from the main branch.
=> Bump version 0.6.dev2

.github/workflows/ci_cd.yml, .github/workflows/nightly-doc-build.yml
Wrongly configured the versions of these two actions in the previous PR for the nightly build. Fixed it with the correct versions for the respective actions.
=> Fixed wrong versioning of the upload artifact and deploy action.

doc/source/conf.py
=> Updated conf.py

pyproject.toml, tests/test_metadata.py
Creating dev release for each repos, will create public release after that.
@mkundu1, I have discarded the old PR, and created this new one. I have pushed the tag as well.
=> Bump version to 0.7.dev1

doc/source/conf.py, pyproject.toml, requirements/requirements_doc.txt
This will fix the current nightly doc build issue.
=> Fix doc build failure

.github/workflows/ci_cd.yml, .github/workflows/nightly-doc-build.yml
=> maint: change pyansys actions

.ci/pull_fluent_image.sh, .github/workflows/ci_cd.yml, README.rst, doc/source/conf.py, doc/source/contributing.rst, doc/source/getting_started/index.rst, doc/source/index.rst, pyproject.toml
Fixing nightly doc build failures.
=> Fix nightly doc build

.github/workflows/ci_cd.yml, .github/workflows/nightly-doc-build.yml, doc/source/conf.py
I'll push the same patch to release branches.
[Issue link](https://github.com/ansys/pyfluent/issues/1593)
=> Update to pyansys action v4

.github/workflows/ci_cd.yml, .github/workflows/nightly-doc-build.yml
Getting the temporal token from the bot app is not used. There is no calls to that step ``get_workflow_token``.
Close #273
=> Removing unused step and fixing secrets

.github/workflows/nightly-doc-build.yml
Try fixing the nightly doc [failure](https://github.com/ansys/pyfluent-visualization/actions/runs/5184463480) which seems to be due to failed docker operations.
=> Use similar login from pyfluent to fix the nightly doc CI

src/ansys/fluent/visualization/post_data_extractor.py, src/ansys/fluent/visualization/pyvista/pyvista_windows_manager.py
Make this repo consistent with the changes made in the meta.py of core repo in https://github.com/ansys/pyfluent/pull/1697
=> Fix viz repo wrt core repo changes.

pyproject.toml
New VTK release candidate finally available
Closes https://github.com/ansys/pyfluent-visualization/issues/289
=> Updating dependency for new VTK release to remove vulnerability

pyproject.toml, requirements/requirements_doc.txt
Added source, documentation and bugtrack urls.
=> Update URLs for PyPi projects

examples/00-postprocessing/post_processing_exhaust_manifold.py
Testing if this fixes doc issues in https://github.com/ansys/pyfluent-visualization/pull/353
=> Update post_processing_exhaust_manifold.py (release 0.8.0 branch)

.github/workflows/ci_cd.yml, .github/workflows/nightly-test-run.yml, README.rst, doc/source/getting_started/index.rst, examples/00-postprocessing/post_processing_exhaust_manifold.py, pyproject.toml, tests/test_metadata.py
Fixing the pyfluent version in dependencies, similar to pyfluent-parametric PR https://github.com/ansys/pyfluent-parametric/pull/253
=> Bump version 0.8.0

examples/00-postprocessing/post_processing_exhaust_manifold.py
Need to wait for the next PyFluent dev release after the visualization updates are merged.
=> Update w.r.t. latest PyFluent changes.

examples/00-postprocessing/post_processing_exhaust_manifold.py, pyproject.toml, tests/test_metadata.py
=> Bump version to v0.13.dev0

pyproject.toml, tests/test_metadata.py
=> build: Bump version to v0.12.0

examples/00-postprocessing/post_processing_exhaust_manifold.py, pyproject.toml, tests/test_metadata.py
=> build: Bump version to v0.14.dev0

pyproject.toml, tests/test_metadata.py
=> build: Bump version to v0.13.0

examples/00-postprocessing/post_processing_exhaust_manifold.py, pyproject.toml, tests/test_metadata.py
=> Bump version to v0.15.dev0

pyproject.toml, tests/test_metadata.py
=> build: Bump version to v0.14.0

.github/workflows/ci_cd.yml, pyproject.toml, tests/test_metadata.py
=> build: Bump version to v0.15.0

.github/workflows/ci_cd.yml, .github/workflows/nightly-test-run.yml, README.rst, doc/source/getting_started/index.rst, pyproject.toml
closes https://github.com/ansys/pyfluent-visualization/issues/461
As title says
=> chore: Support Python 3.13

pyproject.toml, tests/test_metadata.py
=> build: Bump version to v0.17.0

.github/workflows/ci_cd.yml, doc/source/conf.py, pyproject.toml, src/ansys/fluent/visualization/matplotlib/__init__.py, src/ansys/fluent/visualization/pyvista/__init__.py, tests/test_metadata.py
=> build: Bump version to v0.18.dev0

pyproject.toml, tests/test_metadata.py, tests/test_post.py
=> build: Bump version to v0.18.0

pyproject.toml, tests/test_metadata.py
=> build: Bump version to v0.19.0

pyproject.toml, tests/test_metadata.py
=> build: Bump version to v0.19.1

Makefile, tests/test_post.py
The AttributeError is random, I can reproduce it locally 1 out of 10 times. For now, let's disable the test for Python 3.13. We'll test this again with future patch release of Python 3.13.
=> test: disable the test only for Python 3.13

.github/workflows/ci_cd.yml, .github/workflows/nightly-doc-build.yml, .github/workflows/nightly-test-run.yml, Makefile
Remove docker images from CI machines after use.
=> build: Remove docker images from CI machines after use.

src/ansys/fluent/visualization/config.py
Update interactivity via env var.
=> chore: Update interactivity via env var.

pyproject.toml, tests/test_metadata.py
=> build: Bump version to v0.21.dev1

README.rst, pyproject.toml, src/ansys/fluent/visualization/graphics/graphics_windows.py, src/ansys/fluent/visualization/graphics/graphics_windows_manager.py, src/ansys/fluent/visualization/graphics/pyvista/renderer.py, src/ansys/fluent/visualization/graphics/single_qt_windows.py, tests/test_visualization.py
=> chore: Update optional dependencies.

pyproject.toml, tests/test_metadata.py
=> build: Bump version to v0.21.0

pyproject.toml, tests/test_metadata.py
=> build: Bump version to v0.22.dev0

pyproject.toml, tests/test_metadata.py
=> build: Bump version to v0.22.0

.github/workflows/ci_cd.yml, pyproject.toml, tests/test_metadata.py
=> build: Bump version to v0.22.1
